#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 21 11:52:37 2020

@author: msvmuthu
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data=pd.read_csv("ex1data1.txt", header=None)
print(data)
data.head()
data.describe()

plt.scatter(data[0],data[1])
plt.xticks(np.arange(5,30,step=5))
plt.yticks(np.arange(-5,30,step=5))
plt.xlabel("Population of City (10,000s)")
plt.ylabel("Profit ($10,000")
plt.title("Profit Prediction")



def computeCost(X,y,theta):
    """
    Take in a numpy array X,y, theta and generate the cost function of using theta as parameter
    in a linear regression model
    """
    m=len(y)
    predictions=X.dot(theta)
    square_err=(predictions - y)**2
    
    return 1/(2*m) * np.sum(square_err)


data_n=data.values
m=data_n[:,0].size
X=np.append(np.ones((m,1)),data_n[:,0].reshape(m,1),axis=1)
y=data_n[:,1].reshape(m,1)
theta=np.zeros((2,1))
computeCost(X,y,theta)
print(data_n)
print(m)
print(X)